---
- hosts: vb

  tasks:
    - ping: ~

    - name: Update APT Package Manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe

    - name: Install cowsay - it's probably important
      apt:
        name: cowsay
      become: true

    - name: Install Git VCS
      become: true
      apt:
        name: git
        state: latest

    - name: Install Nginx web server
      become: true
      apt:
        name: nginx
        state: latest

    - name: Install MySQL DB server
      become: true
      apt:
        name: mysql-server
        state: latest

    - name: Add PHP 7 PPA repository
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP packages
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - php7.2-cli
        - php7.2-curl
        - php7.2-fpm
        - php7.2-intl
        - php7.2-mysql

    - name: Set date.timezone for CLI
      become: true
      lineinfile:
        path: /etc/php/7.2/cli/php.ini
        regexp: "date.timezone"
        line: "date.timezone = UTC"

    - name: Set date.timezone for FPM
      become: true
      lineinfile:
        path: /etc/php/7.2/fpm/php.ini
        regexp: "date.timezone"
        line: "date.timezone = UTC"
